### PR TITLE
Add qryn to destinations

### PR DESCRIPTION
**Pull request by lmangani**
This PR implements a dedicated [qryn](https://qryn.dev) Odigos destination based off the original Grafana destination. 

Opening draft PR for peer-review and testing

image

### CODE REVIEW

**Comment by lmangani** [comment]
@edeNFed as per suggestion in #33 we're submitting a standalone destination for [qryn](https://qryn.dev)

**Comment by edeNFed** [comment]
Thanks for contributing @lmangani looks great!I am on vacation so I'll be able to merge it next week. Sorry for the delay.

**Comment by lmangani** [comment]
Thanks @edeNFed no worries, we'll do some testing in the meantime. Enjoy your holidays!

**Comment by lmangani** [comment]
@edeNFed hope you had a nice break! do you have any bandwidth to help us land this PR?

**Review by edeNFed — APPROVED** [review]

**Comment by edeNFed** [comment]
Hi @lmangani sorry for the delay!
looks great, merging.

**Comment by lmangani** [comment]
Thanks @edeNFed let us know if this makes it in a new release so we can promote it to our audience

**Comment by edeNFed** [comment]
Hi @lmangani version `v0.1.36` released with qryn destination inside 😄

**Pull request merged**
