### PR TITLE
Changed markdown image tag to Frame (#649)

### PR DESCRIPTION
**Pull request by biplobsd**
Fixed : #649

### CODE REVIEW

**Comment by biplobsd** [comment]
@blumamir Kindly review.

**Comment by biplobsd** [comment]
@edeNFed Kindly have a look.

**Review by edeNFed — APPROVED** [review]

**Review by blumamir — APPROVED** [review]
Thanks! @biplobsd

**Comment by biplobsd** [comment]
https://biplobsd.me/blogs/view/contributing-to-open-source-my-hacktoberfest-experience.md

I wrote a blog about my hacktoberfest journey. I mentioned @edeNFed  and @blumamir  to on my blog.

**Pull request merged**
