### PR TITLE
fix: respect `KUBECONFIG` env var

### PR DESCRIPTION
**Pull request by rauno56**
Many linux users force config location to `XDG_CONFIG_HOME` instead of home folder and have `KUBECONFIG` env variable set. Current install script did not respect that and failed if that was the case.

Fix checks the environment for mentioned env var and uses that if set. If `KUBECONFIG` is not set, the behavior is unchanged.

### CODE REVIEW

**Review by blumamir — APPROVED** [review]

**Comment by rauno56** [comment]
I see there's another location that assumes the config is always in the default location. It's in the frontend code.

**Comment by blumamir** [comment]
> I see there's another location that assumes the config is always in the default location. It's in the frontend code.

Yeah that makes sense, good catch

I think the `common` module might be a good place for it

**Comment by blumamir** [comment]
perhaps [here](https://github.com/keyval-dev/odigos/blob/main/common/utils/env.go)?

**Comment by rauno56** [comment]
Actually... now when I see that the used function comes from k8s client package, it makes me think the bug is there, but regardless... I'll fix it here first.

**Comment by rauno56** [comment]
Made the move and reused it in frontend. Should I do anything about changed deps in modules as well?

**Review by blumamir — APPROVED** [review]

**Comment by blumamir** [comment]
> Should I do anything about changed deps in modules as well?

Amazing! thanks

Do you mean about the `go.mod` and `go.sum` files?

**Comment by rauno56** [comment]
> Do you mean about the go.mod and go.sum files?

That's right.

**Pull request merged**
