### PR TITLE
fix: change the logo as required 

### LINKED ISSUE #486: Remove black background from Odigos logo
Change Odigos logo background to be transparent instead of black.

### PR DESCRIPTION
**Pull request by ankur0904**
Fix #486

cc @edeNFed

### CODE REVIEW

**Comment by ankur0904** [comment]
@edeNFed Please review the PR.

**Comment by edeNFed** [comment]
@ankur0904 This is the logo I was referring to: (taken from odigos UI)

Screenshot 2023-10-15 at 1 16 14 PM

**Comment by ankur0904** [comment]
@edeNFed How can I get the logo?

**Comment by ankur0904** [comment]
> odigos



> @ankur0904 This is the logo I was referring to: (taken from odigos UI)
> 
> Screenshot 2023-10-15 at 1 16 14 PM

@edeNFed Should I use this logo exactly?

**Comment by ankur0904** [comment]
@edeNFed Please review the changes.

**Pull request closed without merging**
