### PR TITLE
Fix Deployment and StatefulSet Name Collision

### LINKED ISSUE #8: Deployment and StatefulSet with same name may overwrite each other
Use generated name for `InstrumentedApplication` instead of fixed name

### PR DESCRIPTION
**Pull request by eugercek**
Fixes #8

### CODE REVIEW

**Comment by eugercek** [comment]
Hi @edeNFed AFAIK since crd names become url for the API server, they must be lowercase. I'm moving to:
- `deployment-name`
- `statefulset-name`

Example error message
```
1.674601193620897e+09   ERROR   controller.deployment   error creating InstrumentedApp object   {"reconciler group": "apps", "reconciler kind": "Deployment", "name": "redis-cart", "namespace": "default", "error": "InstrumentedApplication.odigos.io \"Deployment-redis-cart\" is invalid: metadata.name: Invalid value: \"Deployment-redis-cart\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"}
```

**Comment by edeNFed** [comment]
tested on my machine and it works great.
Looks good to me, feel free to merge if you finished
Thanks!

**Comment by eugercek** [comment]
I was going to test, thanks for your time.

**Comment by edeNFed** [comment]
Merged, thank you @eugercek

**Pull request merged**
