### PR TITLE
Signing containers using cosign.

### PR DESCRIPTION
**Pull request by prady0t**
Fixes: #566

### CODE REVIEW

**Comment by prady0t** [comment]
This is my first time working with github actions. Any feedback is highly valuable to me.

**Comment by edeNFed** [comment]
Hi @prady0t 
I think you should do the signin as part of the release workflow. 
You can find the workflow at: `.github/workflows/main.yaml`

**Comment by prady0t** [comment]
Ok so basically sign every image after it's build, like after this build:  
https://github.com/keyval-dev/odigos/blob/b245d0ed898439c5799867ba7b45270e3bc247c5/.github/workflows/main.yml#L69C6-L69C6

Do something like: 
```
      - name: Sign the container image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign sign \
          ghcr.io/keyval-dev/odigos/odiglet@${{ steps.push-step.outputs.digest }}
```
And so on for all image builds?

**Comment by edeNFed** [comment]
yes I think so

**Comment by prady0t** [comment]
@edeNFed did the changes. Please have a look.

**Comment by edeNFed** [comment]
@prady0t  I think we should sign also the images uploaded to docker hub for example keyval-dev/odigos-autoscaler

**Comment by prady0t** [comment]
Please review.
@edeNFed

**Pull request closed without merging**
