### PR TITLE
[Enhancement] :Making the hacktoberfest section Appealing 

### PR DESCRIPTION
**Pull request by shelar1423**
Making the hacktoberfest section Appealing  by adding emojis and rephrasing text.

Before:
image

After :
image

### CODE REVIEW

**Comment by shelar1423** [comment]
hey @edeNFed is this going to be implemented or you suggest me to close this PR?

**Comment by shelar1423** [comment]
@edeNFed

**Review by blumamir — APPROVED** [review]
Awesome!!

Thanks for this 🎉

**Comment by shelar1423** [comment]
Your welcome @blumamir  thanks for approving this for merging 😄

**Comment by shelar1423** [comment]
Your welcome @blumamir  thanks for approving this for merging 😄, It's ready to merge now , looking forward for more contributions 💪

**Pull request merged**
